import type { AdminFile, TaskRecord } from './admin'
import { newAdminId } from './admin'
import { sessionKey } from './diff'
import type { MetaMap, Session, Settings } from '../types'

/**
 * Personal tasks (P5-01): normalised records in the per-profile store with
 * stable ids, revisions and tombstones. Source-imported deadlines remain
 * source-owned sessions with progress metadata — only user tasks live here.
 */

/** Stable logical identity for notification routing — never regenerated by
 *  title/due edits. */
export const taskEventKey = (t: Pick<TaskRecord, 'id'>) => `task:${t.id}`

/** Present a task as a synthetic key-date session for the existing calendar/
 *  reminder/Today pipelines. The id and calendar UID keep the exact pre-P5
 *  `custom-<id>` form so subscribed/imported calendars see the same events. */
export function taskToSession(t: TaskRecord): Session {
  return {
    id: `custom-${t.id}`,
    calendarUid: `custom-${t.id}`,
    eventKey: taskEventKey(t),
    title: t.title,
    day: '',
    dateISO: t.dueISO,
    start: t.dueTime ?? '',
    end: '',
    room: '',
    groups: '',
    tutor: '',
    subject: t.title,
    isSpecialism: false,
    isSelfStudy: false,
    isOptional: false,
    isKeyDate: true,
  }
}

/** Status/notes of tasks, merged over the session metadata map so display
 *  consumers (Today strip, reminders, Tasks rows) read one shape. These
 *  entries are read-only views — writes go through the task records. */
export function overlayTaskMeta(metaMap: MetaMap, tasks: TaskRecord[]): MetaMap {
  if (tasks.length === 0) return metaMap
  const out = { ...metaMap }
  for (const t of tasks) {
    out[taskEventKey(t)] = { status: t.status, note: t.notes, at: t.at }
  }
  return out
}

/**
 * One-time migration of the old Settings.customKeyDates entries into task
 * records. The record keeps the OLD id (so `custom-<id>` session/calendar
 * identity is unchanged) and adopts any status/note the user had saved
 * against the legacy owner key.
 */
export function migrateCustomKeyDates(
  settings: Settings,
  metaMap: MetaMap,
  admin: AdminFile
): { admin: AdminFile; migrated: boolean } {
  const legacy = settings.customKeyDates ?? []
  if (legacy.length === 0) return { admin, migrated: false }
  const existing = new Set(admin.tasks.map((t) => t.id))
  const tombstoned = admin.deleted ?? {}
  const added: TaskRecord[] = []
  for (const c of legacy) {
    if (existing.has(c.id) || tombstoned[`tasks:${c.id}`]) continue
    // The legacy owner key (Phase 2 eventKey of the synthetic session).
    const legacyKey = sessionKey({
      id: `custom-${c.id}`,
      title: c.title,
      day: '',
      dateISO: c.dateISO,
      start: c.start ?? '',
      end: '',
      room: '',
      groups: '',
      tutor: '',
      subject: c.title,
      isSpecialism: false,
      isSelfStudy: false,
      isOptional: false,
      isKeyDate: true,
    })
    const meta = metaMap[legacyKey]
    added.push({
      id: c.id,
      title: c.title,
      dueISO: c.dateISO,
      dueTime: c.start || undefined,
      status: meta?.status ?? 'todo',
      notes: meta?.note || undefined,
      at: Date.now(),
    })
  }
  if (added.length === 0) return { admin, migrated: true }
  return { admin: { ...admin, tasks: [...admin.tasks, ...added] }, migrated: true }
}

/** Duplicate: fresh id and revision; never inherits completion. */
export function duplicateTask(t: TaskRecord): TaskRecord {
  return {
    ...t,
    id: newAdminId(),
    title: `${t.title} (copy)`,
    status: 'todo',
    completedISO: undefined,
    at: Date.now(),
  }
}
