import { chromium } from './runtime/node_modules/playwright/index.mjs';
import fs from 'node:fs';import path from 'node:path';
const root=path.resolve('handoff/designs');const entries=JSON.parse(fs.readFileSync(root+'/manifest.json'));const browser=await chromium.launch({headless:true});const page=await browser.newPage();await page.route('**/*',r=>r.request().url().startsWith('file:')?r.continue():r.abort());const qa=[];
for(const [name,title] of Object.entries(entries)){
 const width=name.includes('desktop')||name==='admin'?1440:390;await page.setViewportSize({width,height:900});await page.goto('file://'+root+'/after-'+name+'.html');await page.screenshot({path:root+'/after-'+name+'.png'});qa.push({name,...await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,height:document.documentElement.scrollHeight}))});
}
await page.setViewportSize({width:390,height:900});await page.goto('file://'+root+'/after-today.html?theme=dark');await page.screenshot({path:root+'/after-today-dark.png'});
const gallerycss='body{margin:0;background:#f4f6fb;font:16px/1.5 system-ui;color:#202940}header{background:#172a40;color:white;padding:36px 5vw}header p{max-width:900px;color:#c7d5e5}h1{margin:0;font-size:34px}nav{position:sticky;top:0;background:white;padding:12px 5vw;display:flex;gap:8px;overflow:auto;z-index:2;border-bottom:1px solid #dce2ed}nav a{white-space:nowrap;padding:8px 12px;background:#eef0ff;border-radius:8px;color:#3e51c7;text-decoration:none;font-size:14px}section{max-width:1500px;margin:40px auto;padding:0 24px;scroll-margin-top:85px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:24px;align-items:start}.pair.mobile{max-width:850px}figure{margin:0}figure img{width:100%;display:block;border-radius:14px;border:1px solid #dce2ed}figcaption{font-weight:650;margin:10px 0;color:#526078}a{color:#3e51c7}.note{color:#526078;max-width:900px}.pill{font-size:12px;text-transform:uppercase;letter-spacing:1px}';
let gallery='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Timetable UI — before and after</title><style>'+gallerycss+'</style><header><div class="pill">Visual audit · 10 September 2026</div><h1>A clearer timetable, at every step</h1><p>Actual current UI on the left. Proposed design on the right. Synthetic data throughout. These are visual specifications, not implemented app changes.</p></header><nav>'+Object.entries(entries).map(([n,t])=>`<a href="#${n}">${t}</a>`).join('')+'</nav>';
for(const [name,title] of Object.entries(entries)){
 const desktop=name.includes('desktop')||name==='admin';
 const pair=`<div class="pair ${desktop?'':'mobile'}"><figure><figcaption>BEFORE · current snapshot</figcaption><img alt="Current ${title}" src="../evidence/before-${name}.png"></figure><figure><figcaption>AFTER · proposed design</figcaption><img alt="Proposed ${title}" src="after-${name}.png"></figure></div>`;
 gallery+=`<section id="${name}"><h2>${title}</h2>${pair}<p><a href="after-${name}.html">Open proposed screen at full size</a></p></section>`;
 const cw=desktop?2960:870;const standalone=`<!doctype html><html><meta charset="utf-8"><style>body{margin:0;background:#edf1f7;font:16px system-ui;color:#202940;padding:24px}.pair{display:flex;gap:24px}figure{margin:0}figcaption{font-size:15px;font-weight:700;margin-bottom:12px}img{display:block;width:${desktop?1440:390}px;border:1px solid #dce2ed;border-radius:12px}h2{margin:0 0 18px;font-size:22px}</style><h2>${title}</h2>${pair}</html>`;
 fs.writeFileSync(root+'/compare-'+name+'.html',standalone);await page.setViewportSize({width:cw,height:1010});await page.goto('file://'+root+'/compare-'+name+'.html');await page.screenshot({path:root+'/compare-'+name+'.png',fullPage:true});
}
gallery+='<section><h2>Dark-theme direction</h2><p class="note">Supplemental proposed screen. Retain semantic colours with independently checked dark-theme contrast.</p><img style="max-width:390px;width:100%;border-radius:16px" src="after-today-dark.png" alt="Proposed Today in dark theme"></section></html>';fs.writeFileSync(root+'/gallery.html',gallery);fs.writeFileSync(root+'/render-qa.json',JSON.stringify(qa,null,2));await browser.close();console.log(qa);
