import test from 'node:test'
import assert from 'node:assert/strict'
import { collections, optionalCollections, validatePayload } from '../../shared/contracts.js'
import { canonical, mergeAdmin } from '../../shared/merge.js'

const empty = () => Object.fromEntries(collections.map((k) => [k, []]))
const basePayload = () => ({
  store: { activeId: 'p1', profiles: [{ id: 'p1', name: 'one', settings: { demo: true, sheetId: '', gid: null } }] },
})

test('legacy payloads without the Phase 5 collections still validate (back-compat)', () => {
  const legacyAdmin = {
    reflections: [], targets: [], meetings: [], observations: [], lessons: [], audits: [],
  }
  assert.doesNotThrow(() => validatePayload({ ...basePayload(), admin: { p1: legacyAdmin } }))
  assert.ok(optionalCollections.every((k) => collections.includes(k)))
})

test('new collection records validate strictly: enums, dates, times, bounds', () => {
  const admin = {
    ...empty(),
    tasks: [{ id: 't1', title: 'Essay', dueISO: '2026-09-10', dueTime: '17:00', status: 'todo', at: 1 }],
    exceptions: [{ id: 'e1', tag: 'SE1A', dateISO: '2026-10-01', kind: 'inset', loggedMins: 300, at: 1 }],
    plans: [{ id: 'w1', parentId: 't1', kind: 'subtask', title: 'Outline', done: false, effortMins: 60, at: 1 }],
    commitments: [{ id: 'c1', title: 'Dentist', dateISO: '2026-09-09', startTime: '18:00', endTime: '19:00', kind: 'appointment', busy: true, at: 1 }],
  }
  assert.doesNotThrow(() => validatePayload({ ...basePayload(), admin: { p1: admin } }))
  const bad = (patch) => ({ ...basePayload(), admin: { p1: { ...admin, ...patch } } })
  assert.throws(() => validatePayload(bad({ tasks: [{ id: 't1', title: 'x', dueISO: '2026-09-10', status: 'later', at: 1 }] })))
  assert.throws(() => validatePayload(bad({ tasks: [{ id: 't1', title: 'x', dueISO: '31/02/2026', status: 'todo', at: 1 }] })))
  assert.throws(() => validatePayload(bad({ commitments: [{ id: 'c1', title: 'x', dateISO: '2026-09-09', startTime: '25:00', endTime: '19:00', kind: 'work', at: 1 }] })))
  assert.throws(() => validatePayload(bad({ exceptions: [{ id: 'e1', tag: 'SE1A', dateISO: '2026-10-01', kind: 'strike', at: 1 }] })))
  assert.throws(() => validatePayload(bad({ plans: [{ id: 'w1', parentId: 't1', kind: 'subtask', title: 'x', effortMins: -5, at: 1 }] })))
})

test('task edits merge per record; identity survives title/due changes; undo beats the tombstone', () => {
  const task = { id: 't1', title: 'Essay', dueISO: '2026-09-10', status: 'todo', at: 5 }
  // Two devices edit the SAME task: newest revision wins whole-record.
  const a = { ...empty(), tasks: [{ ...task, title: 'Essay v2', at: 8 }] }
  const b = { ...empty(), tasks: [{ ...task, status: 'doing', at: 9 }] }
  const merged = mergeAdmin(a, b)
  assert.equal(merged.tasks.length, 1)
  assert.equal(merged.tasks[0].status, 'doing')
  assert.equal(merged.tasks[0].id, 't1') // identity never regenerated by edits
  // Two DIFFERENT tasks edited concurrently both survive.
  const c = { ...empty(), tasks: [{ ...task, at: 8 }, { id: 't2', title: 'Other', dueISO: '2026-09-12', status: 'todo', at: 3 }] }
  assert.equal(mergeAdmin(c, b).tasks.length, 2)
  // Delete on one device, then undo writes a NEWER revision than the tombstone.
  const withDelete = { ...empty(), deleted: { 'tasks:t1': 10 } }
  assert.equal(mergeAdmin(a, withDelete).tasks.length, 0) // tombstone wins over rev 8
  const undone = { ...empty(), tasks: [{ ...task, at: 11 }] }
  const backAgain = mergeAdmin(mergeAdmin(a, withDelete), undone)
  assert.equal(backAgain.tasks.length, 1) // rev 11 > tombstone 10 — resurrected deliberately
  // Merges converge regardless of direction.
  assert.equal(canonical(mergeAdmin(a, b)), canonical(mergeAdmin(b, a)))
})

test('commitments and plan children merge with tombstones like every other record', () => {
  const c1 = { id: 'c1', title: 'Dentist', dateISO: '2026-09-09', startTime: '18:00', endTime: '19:00', kind: 'appointment', at: 4 }
  const left = { ...empty(), commitments: [c1], plans: [{ id: 'w1', parentId: 't1', kind: 'block', title: 'Study', at: 2 }] }
  const right = { ...empty(), deleted: { 'plans:w1': 3 } }
  const merged = mergeAdmin(left, right)
  assert.equal(merged.commitments.length, 1)
  assert.equal(merged.plans.length, 0)
  // Editing an interval keeps identity and unrelated fields.
  const edited = { ...empty(), commitments: [{ ...c1, startTime: '18:30', at: 6 }] }
  const out = mergeAdmin(left, edited).commitments[0]
  assert.equal(out.id, 'c1')
  assert.equal(out.title, 'Dentist')
  assert.equal(out.startTime, '18:30')
})
